# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: 6.x
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
    - name: Publish to nuget.org
      run: nuget push "Source\bin\Release\FigmaDotNet.*.nupkg" -ApiKey ${{ secrets.NUGET_TOKEN }}
      
